version: "3.9"

services:
  database:
    image: postgres
    env_file:
      - .env/development/database
    volumes:
      - db_data:/var/lib/postgresql/data

  web:
    image: budvest
    ports:
      - "3000:3000"
      - "4000:4000"
    tty: true
    env_file:
      - .env/development/web
      - .env/development/database
    volumes:
      - .:/budvest
      - bundle_cache:/bundle_cache

volumes:
  db_data:
  bundle_cache:
